FROM python:3.10-slim

# Sistem bağımlılıkları (Scapy ve Kafka için gerekli)
RUN apt-get update && apt-get install -y \
    libpcap-dev \
    tcpdump \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# Varsayılan komut (Compose dosyasında bunu ezeceğiz)
CMD ["python", "sniffer.py"]